NWEB.Practice.T01.Web/Areas/Admin/Controllers/FlowerController.cs
using NWEB.Practice.T01.Web.Areas.Admin.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NWEB.Practice.T01.Web.Areas.Admin.ViewModel;
using System.IO;
using System.Web.WebPages;
using Microsoft.Ajax.Utilities;
using NWEB.Practice.T01.Core.Models;

namespace NWEB.Practice.T01.Web.Areas.Admin.Controllers
{
    public class FlowerController : Controller
    {
        // GET: Admin/Flower
        FlowerShopDbContext _db = new FlowerShopDbContext();
        public ActionResult Index()
        {
            return View(FlowerBusiness.GetAll());
        }

        // GET: Admin/Flower/Details/5
        public ActionResult Details(int id)
        {
            return View(FlowerBusiness.FindById(id));
        }

        public void LoadDropdownCategory()
        {
            var cate = CategoryBusiness.GetAll().ToList();
            // Tạo SelectList
            SelectList cateList = new SelectList(cate, "Id", "CategoryName");
            ViewBag.CategoryList = cateList;
        }
        public void LoadDropdownFlower()
        {
            var result = FlowerBusiness.GetAll().ToList();
            // Tạo SelectList
            SelectList flowerList = new SelectList(result, "Id", "FlowerName");
            // Set vào ViewBag
            ViewBag.FlowerList = flowerList;
        }
        public void LoadDropdownColor()
        {
            var result = ColorBusiness.GetAll().ToList();
            // Tạo SelectList
            SelectList colorList = new SelectList(result, "Id", "ColorName");
            // Set vào ViewBag
            ViewBag.ColorList = colorList;
        }

        // GET: Admin/Flower/Create
        public ActionResult Create()
        {
            LoadDropdownColor();
            LoadDropdownCategory();
            return View();
        }
        
        // POST: Admin/Flower/Create
        [HttpPost]
        public ActionResult Create(FlowerViewModel obj,HttpPostedFileBase image)
        {
            try
            {
                // TODO: Add insert logic here
                if (image != null)
                {
                    obj.Image = LoadImage(image);
                }
                FlowerBusiness.Create(obj);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public string LoadImage(HttpPostedFileBase image)
        {
            if (image != null)
            {
                string fileName = Path.GetFileName(image.FileName);
                string path = Path.Combine(Server.MapPath("~/Areas/Admin/Content/ImageFlower"),fileName );
                image.SaveAs(path);
                return "/Areas/Admin/Content/ImageFlower/" + fileName;
            }

            return null;
        }
        // GET: Admin/Flower/Edit/5
        public ActionResult Edit(int id)
        {
            LoadDropdownCategory();
            LoadDropdownColor();
            return View(FlowerBusiness.FindById(id));
        }

        // POST: Admin/Flower/Edit/5
        [HttpPost]
        public ActionResult Edit(FlowerViewModel obj, HttpPostedFileBase image)
        {
            try
            {
                // TODO: Add update logic here
                if (image != null)
                {
                    obj.Image = LoadImage(image);
                }
                FlowerBusiness.Edit(obj);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Flower/Delete/5
        public ActionResult Delete(int id)
        {

            FlowerBusiness.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult SaleOff()
        {
            List<CategoryViewModel> CountryList = CategoryBusiness.GetAll();
            ViewBag.CountryList = new SelectList(CountryList, "Id", "CategoryName");
            return View();
        }

        public JsonResult GetStateList(int CategoryId)
        {
            _db.Configuration.ProxyCreationEnabled = false;
            List<FlowerViewModel> StateList = FlowerBusiness.GetAll().Where(x => x.CategoryId == CategoryId).ToList();
            return Json(StateList, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaleOff([Bind(Exclude = "Id")] CategoryFlowerViewModel flower)
        {
            if (!ModelState.IsValid) return null;
            if (flower.FlowerName.IsEmpty() || flower.FlowerName.IsNullOrWhiteSpace())
            {
                var flowerY = FlowerBusiness.GetAll().Where(f => f.CategoryId == flower.CategoryId).ToList();
                foreach (var flowerViewModel in flowerY)
                {
                    flowerViewModel.SalePrice = flowerViewModel.Price * (1 - flower.SaleOff * 0.01m);
                    FlowerBusiness.Edit(flowerViewModel);
                }
                return RedirectToAction("Index");
            }

            var flowerX = FlowerBusiness.GetAll()
                .FirstOrDefault(f => f.CategoryId == flower.CategoryId && f.FlowerName == flower.FlowerName);
            if (flowerX == null) return HttpNotFound();
            flowerX.SalePrice = (flowerX.Price * (1 - flower.SaleOff * 0.01m));
            FlowerBusiness.Edit(flowerX);
            return RedirectToAction("Index");
        }

    }
}

NWEB.Practice.T01.Web/Controllers/FlowersController.cs
using NWEB.Practice.T01.DataAccessLayer.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NWEB.Practice.T01.Web.Controllers
{
    public class FlowersController : Controller
    {
        private FlowerService flower = new FlowerService();
        // GET: Flowers
        public ActionResult Index()
        {
            return View(flower.GetAll());
        }

        public ActionResult GetAllFlowerById(int categoryId)
        {
            var resutl = flower.GetAll().Where(x => x.CategoryId == categoryId).ToList();
            return View(resutl);
        }
    }
}

NWEB.Practice.T01.Web/Areas/Admin/Views/Flower/Create.cshtml
@model NWEB.Practice.T01.Web.Areas.Admin.ViewModel.FlowerViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Flower", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>FlowerViewModel</h4>
        @Html.Partial("_PartialCreateOrEdit")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(function () {
            $('#StoreDate').datetimepicker({
                sideBySide: true
            });
        });
    </script>
}

NWEB.Practice.T01.Web/Areas/Admin/Views/Flower/Edit.cshtml
@model NWEB.Practice.T01.Web.Areas.Admin.ViewModel.FlowerViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Flower", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.HiddenFor(model => model.Id)

        @Html.Partial("_PartialCreateOrEdit")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Back to List", "Index")

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
    </script>
}

NWEB.Practice.T01.Web/Areas/Admin/Views/Flower/Index.cshtml
@model IEnumerable<NWEB.Practice.T01.Web.Areas.Admin.ViewModel.FlowerViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FlowerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ColorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SalePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StoreDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StoreInventory)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FlowerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ColorId)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.Image)*@
            <img src="@item.Image" width="50" height="50" alt="anh khong hien thi" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SalePrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StoreDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StoreInventory)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

NWEB.Practice.T01.Web/Areas/Admin/Views/Flower/SaleOff.cshtml
@model NWEB.Practice.T01.Web.Areas.Admin.ViewModel.CategoryFlowerViewModel
@{
    ViewBag.Title = "SaleOff";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("SaleOff", "Flower", FormMethod.Post, new { @id = "FormSaleOff" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            @if (ViewBag.CountryList != null)
            {
                <div class="col-md-10">
                    
                     @Html.DropDownListFor(model => model.CategoryId, ViewBag.CountryList as SelectList, "--Select Country--", new { @class = "form-control" })
                </div>
            }
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FlowerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FlowerName, new SelectList(" "), "--Select State--", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SaleOff, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleOff, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleOff, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Back to List", "Index")

            </div>
        </div>

    </div>
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $(document).ready(function () {
        $("#CategoryId").change(function () {
            $.get("../Flower/GetStateList",
                { CategoryId: $("#CategoryId").val() },
                function (data) {

                    $("#FlowerName").empty();
                    $("#FlowerName").append("<option value=''>" + "--Select State1--" + "</option>");
                    $.each(data,
                        function (index, row) {
                            $("#FlowerName").append("<option value='" + row.FlowerName + "'>" + row.FlowerName + "</option>")
                        });
                });
        });
    });
</script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Areas/Admin/Content/vendor/jquery/ValidateForm.js"></script>

NWEB.Practice.T01.Web/Areas/Admin/Views/Flower/_PartialCreateOrEdit.cshtml
@using NWEB.Practice.T01.Web.Extension
@model NWEB.Practice.T01.Web.Areas.Admin.ViewModel.FlowerViewModel

@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("CategoryId", (IEnumerable<SelectListItem>)ViewBag.CategoryList, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.FlowerName, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.FlowerName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.FlowerName, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.ColorId, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("ColorId", (IEnumerable<SelectListItem>)ViewBag.ColorList, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ColorId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @* @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
        @Html.HiddenFor(model => model.Image)
        @if (Model != null && Model.Image != null)
        {
            <img src="@Model.Image" height="100" width="100"/>
        }
        <input type="file" id="Image" name="Image" />
        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.SalePrice, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.SalePrice, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.SalePrice, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.StoreDate, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DatePickerFor(model => model.StoreDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.StoreDate, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.StoreInventory, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.StoreInventory, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.StoreInventory, "", new { @class = "text-danger" })
    </div>
</div>